### ISSUE TITLE
Doesn't show git difference for "properties" extension file.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex-node-server#16]
![GitDifference](https://user-images.githubusercontent.com/65342122/87274363-3c8d1080-c4f9-11ea-9746-d9015d773085.PNG)

**Comment by neel1996** [comment]
@Nageswari-droid  The fix has been merged to the #gitconvex-package. Re-test it and share your feedback

**Comment by Nageswari-droid** [comment]
Issue fixed. 
![gitDiff](https://user-images.githubusercontent.com/65342122/87389837-2c426780-c5c5-11ea-9823-6513e507b9ef.PNG)
