### ISSUE TITLE
Shows "No commi logs" for large repos.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex-node-server#32]
![commitIssue](https://user-images.githubusercontent.com/65342122/89519476-0d1cab80-d7fa-11ea-8ed7-e01fce35cc41.PNG)

**Comment by neel1996** [comment]
Fixed with - https://github.com/neel1996/gitconvex-server/commit/2b4cbbcf6635fd2bd1c15772a5ddc9289ea42f6a
