### ISSUE TITLE
Error in staging a deleted file.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex-node-server#43]
![stagingErrorNew](https://user-images.githubusercontent.com/65342122/92578187-29a07d80-f2a9-11ea-9c82-24c3a0c5fe70.PNG)

**Comment by neel1996** [comment]
The file input validation module fiddled with the stage item API leading to this bug

**Comment by neel1996** [comment]
@Nageswari-droid  Issue resolved. Retest again

**Comment by Nageswari-droid** [comment]
Tested again. Now its working correctly.
